name: CI
on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: pnpm
            - name: Install deps
              run: pnpm install --frozen-lockfile
            - name: ESLint
              run: pnpm run ci:lint
            - name: Typecheck
              run: pnpm run ci:typecheck
            - name: Prettier
              run: pnpm run ci:fmt
            - name: Build
              run: pnpm run ci:build

    test:
        needs: [lint]
        strategy:
            matrix:
                node-version: [22.x, 24.x, 26.x]
                eslint-version: [8, 9, 10]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Install deps
              run: pnpm install --frozen-lockfile
            - name: Setup eslint
              run: pnpm add -D eslint@${{ matrix.eslint-version }}
            - name: Tests
              run: pnpm run ci:tests

    integration-tests:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: pnpm
            - name: Install deps
              run: pnpm install --frozen-lockfile
            - name: Build
              run: pnpm run build
            - name: Lint examples
              run: pnpm --recursive --filter './examples/*' run lint
